project:
  type: website

website:
  title: "IS428-VA4BIProject"
  navbar:
    left:
      - text: Introduction
        href: Intro.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

